# Generated by Django 5.2.6 on 2025-09-24 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('eSewa', 'eSewa'), ('Khalti', 'Khalti'), ('Fonepay', 'Fonepay'), ('IMEPay', 'IME Pay'), ('BankTransfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('transaction_id', models.CharField(help_text='Transaction ID from gateway', max_length=255, unique=True)),
                ('reference_code', models.CharField(blank=True, help_text='Optional ref. like Khalti token/eSewa refId', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app1.course')),
                ('sponsorship', models.ForeignKey(blank=True, help_text='If this payment is part of a sponsorship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app1.sponsorship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
