# Generated by Django 5.2.6 on 2025-09-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
